// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sec1.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from sec1.proto</summary>
public static partial class Sec1Reflection {

  #region Descriptor
  /// <summary>File descriptor for sec1.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static Sec1Reflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpzZWMxLnByb3RvGg9jb25zdGFudHMucHJvdG8iKQoLU2Vzc2lvbkNtZDES",
          "GgoSY2xpZW50X3ZlcmlmeV9kYXRhGAIgASgMIkMKDFNlc3Npb25SZXNwMRIX",
          "CgZzdGF0dXMYASABKA4yBy5TdGF0dXMSGgoSZGV2aWNlX3ZlcmlmeV9kYXRh",
          "GAMgASgMIiQKC1Nlc3Npb25DbWQwEhUKDWNsaWVudF9wdWJrZXkYASABKAwi",
          "VQoMU2Vzc2lvblJlc3AwEhcKBnN0YXR1cxgBIAEoDjIHLlN0YXR1cxIVCg1k",
          "ZXZpY2VfcHVia2V5GAIgASgMEhUKDWRldmljZV9yYW5kb20YAyABKAwiqQEK",
          "C1NlYzFQYXlsb2FkEhkKA21zZxgBIAEoDjIMLlNlYzFNc2dUeXBlEhsKA3Nj",
          "MBgUIAEoCzIMLlNlc3Npb25DbWQwSAASHAoDc3IwGBUgASgLMg0uU2Vzc2lv",
          "blJlc3AwSAASGwoDc2MxGBYgASgLMgwuU2Vzc2lvbkNtZDFIABIcCgNzcjEY",
          "FyABKAsyDS5TZXNzaW9uUmVzcDFIAEIJCgdwYXlsb2FkKmcKC1NlYzFNc2dU",
          "eXBlEhQKEFNlc3Npb25fQ29tbWFuZDAQABIVChFTZXNzaW9uX1Jlc3BvbnNl",
          "MBABEhQKEFNlc3Npb25fQ29tbWFuZDEQAhIVChFTZXNzaW9uX1Jlc3BvbnNl",
          "MRADYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ConstantsReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Sec1MsgType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::SessionCmd1), global::SessionCmd1.Parser, new[]{ "ClientVerifyData" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SessionResp1), global::SessionResp1.Parser, new[]{ "Status", "DeviceVerifyData" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SessionCmd0), global::SessionCmd0.Parser, new[]{ "ClientPubkey" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SessionResp0), global::SessionResp0.Parser, new[]{ "Status", "DevicePubkey", "DeviceRandom" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Sec1Payload), global::Sec1Payload.Parser, new[]{ "Msg", "Sc0", "Sr0", "Sc1", "Sr1" }, new[]{ "Payload" }, null, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
/// A message must be of type Cmd0 / Cmd1 / Resp0 / Resp1 
/// </summary>
public enum Sec1MsgType {
  [pbr::OriginalName("Session_Command0")] SessionCommand0 = 0,
  [pbr::OriginalName("Session_Response0")] SessionResponse0 = 1,
  [pbr::OriginalName("Session_Command1")] SessionCommand1 = 2,
  [pbr::OriginalName("Session_Response1")] SessionResponse1 = 3,
}

#endregion

#region Messages
/// <summary>
/// Data structure of Session command1 packet 
/// </summary>
public sealed partial class SessionCmd1 : pb::IMessage<SessionCmd1>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SessionCmd1> _parser = new pb::MessageParser<SessionCmd1>(() => new SessionCmd1());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SessionCmd1> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Sec1Reflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SessionCmd1() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SessionCmd1(SessionCmd1 other) : this() {
    clientVerifyData_ = other.clientVerifyData_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SessionCmd1 Clone() {
    return new SessionCmd1(this);
  }

  /// <summary>Field number for the "client_verify_data" field.</summary>
  public const int ClientVerifyDataFieldNumber = 2;
  private pb::ByteString clientVerifyData_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString ClientVerifyData {
    get { return clientVerifyData_; }
    set {
      clientVerifyData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SessionCmd1);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SessionCmd1 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ClientVerifyData != other.ClientVerifyData) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ClientVerifyData.Length != 0) hash ^= ClientVerifyData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ClientVerifyData.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(ClientVerifyData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ClientVerifyData.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(ClientVerifyData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ClientVerifyData.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(ClientVerifyData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SessionCmd1 other) {
    if (other == null) {
      return;
    }
    if (other.ClientVerifyData.Length != 0) {
      ClientVerifyData = other.ClientVerifyData;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 18: {
          ClientVerifyData = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 18: {
          ClientVerifyData = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Data structure of Session response1 packet 
/// </summary>
public sealed partial class SessionResp1 : pb::IMessage<SessionResp1>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SessionResp1> _parser = new pb::MessageParser<SessionResp1>(() => new SessionResp1());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SessionResp1> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Sec1Reflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SessionResp1() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SessionResp1(SessionResp1 other) : this() {
    status_ = other.status_;
    deviceVerifyData_ = other.deviceVerifyData_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SessionResp1 Clone() {
    return new SessionResp1(this);
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 1;
  private global::Status status_ = global::Status.Success;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Status Status {
    get { return status_; }
    set {
      status_ = value;
    }
  }

  /// <summary>Field number for the "device_verify_data" field.</summary>
  public const int DeviceVerifyDataFieldNumber = 3;
  private pb::ByteString deviceVerifyData_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString DeviceVerifyData {
    get { return deviceVerifyData_; }
    set {
      deviceVerifyData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SessionResp1);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SessionResp1 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Status != other.Status) return false;
    if (DeviceVerifyData != other.DeviceVerifyData) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Status != global::Status.Success) hash ^= Status.GetHashCode();
    if (DeviceVerifyData.Length != 0) hash ^= DeviceVerifyData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Status != global::Status.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Status);
    }
    if (DeviceVerifyData.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(DeviceVerifyData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Status != global::Status.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Status);
    }
    if (DeviceVerifyData.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(DeviceVerifyData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Status != global::Status.Success) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
    }
    if (DeviceVerifyData.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(DeviceVerifyData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SessionResp1 other) {
    if (other == null) {
      return;
    }
    if (other.Status != global::Status.Success) {
      Status = other.Status;
    }
    if (other.DeviceVerifyData.Length != 0) {
      DeviceVerifyData = other.DeviceVerifyData;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Status = (global::Status) input.ReadEnum();
          break;
        }
        case 26: {
          DeviceVerifyData = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Status = (global::Status) input.ReadEnum();
          break;
        }
        case 26: {
          DeviceVerifyData = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Data structure of Session command0 packet 
/// </summary>
public sealed partial class SessionCmd0 : pb::IMessage<SessionCmd0>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SessionCmd0> _parser = new pb::MessageParser<SessionCmd0>(() => new SessionCmd0());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SessionCmd0> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Sec1Reflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SessionCmd0() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SessionCmd0(SessionCmd0 other) : this() {
    clientPubkey_ = other.clientPubkey_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SessionCmd0 Clone() {
    return new SessionCmd0(this);
  }

  /// <summary>Field number for the "client_pubkey" field.</summary>
  public const int ClientPubkeyFieldNumber = 1;
  private pb::ByteString clientPubkey_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString ClientPubkey {
    get { return clientPubkey_; }
    set {
      clientPubkey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SessionCmd0);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SessionCmd0 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ClientPubkey != other.ClientPubkey) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ClientPubkey.Length != 0) hash ^= ClientPubkey.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ClientPubkey.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(ClientPubkey);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ClientPubkey.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(ClientPubkey);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ClientPubkey.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(ClientPubkey);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SessionCmd0 other) {
    if (other == null) {
      return;
    }
    if (other.ClientPubkey.Length != 0) {
      ClientPubkey = other.ClientPubkey;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          ClientPubkey = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          ClientPubkey = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Data structure of Session response0 packet 
/// </summary>
public sealed partial class SessionResp0 : pb::IMessage<SessionResp0>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SessionResp0> _parser = new pb::MessageParser<SessionResp0>(() => new SessionResp0());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SessionResp0> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Sec1Reflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SessionResp0() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SessionResp0(SessionResp0 other) : this() {
    status_ = other.status_;
    devicePubkey_ = other.devicePubkey_;
    deviceRandom_ = other.deviceRandom_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SessionResp0 Clone() {
    return new SessionResp0(this);
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 1;
  private global::Status status_ = global::Status.Success;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Status Status {
    get { return status_; }
    set {
      status_ = value;
    }
  }

  /// <summary>Field number for the "device_pubkey" field.</summary>
  public const int DevicePubkeyFieldNumber = 2;
  private pb::ByteString devicePubkey_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString DevicePubkey {
    get { return devicePubkey_; }
    set {
      devicePubkey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "device_random" field.</summary>
  public const int DeviceRandomFieldNumber = 3;
  private pb::ByteString deviceRandom_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString DeviceRandom {
    get { return deviceRandom_; }
    set {
      deviceRandom_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SessionResp0);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SessionResp0 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Status != other.Status) return false;
    if (DevicePubkey != other.DevicePubkey) return false;
    if (DeviceRandom != other.DeviceRandom) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Status != global::Status.Success) hash ^= Status.GetHashCode();
    if (DevicePubkey.Length != 0) hash ^= DevicePubkey.GetHashCode();
    if (DeviceRandom.Length != 0) hash ^= DeviceRandom.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Status != global::Status.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Status);
    }
    if (DevicePubkey.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(DevicePubkey);
    }
    if (DeviceRandom.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(DeviceRandom);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Status != global::Status.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Status);
    }
    if (DevicePubkey.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(DevicePubkey);
    }
    if (DeviceRandom.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(DeviceRandom);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Status != global::Status.Success) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
    }
    if (DevicePubkey.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(DevicePubkey);
    }
    if (DeviceRandom.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(DeviceRandom);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SessionResp0 other) {
    if (other == null) {
      return;
    }
    if (other.Status != global::Status.Success) {
      Status = other.Status;
    }
    if (other.DevicePubkey.Length != 0) {
      DevicePubkey = other.DevicePubkey;
    }
    if (other.DeviceRandom.Length != 0) {
      DeviceRandom = other.DeviceRandom;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Status = (global::Status) input.ReadEnum();
          break;
        }
        case 18: {
          DevicePubkey = input.ReadBytes();
          break;
        }
        case 26: {
          DeviceRandom = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Status = (global::Status) input.ReadEnum();
          break;
        }
        case 18: {
          DevicePubkey = input.ReadBytes();
          break;
        }
        case 26: {
          DeviceRandom = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Payload structure of session data 
/// </summary>
public sealed partial class Sec1Payload : pb::IMessage<Sec1Payload>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Sec1Payload> _parser = new pb::MessageParser<Sec1Payload>(() => new Sec1Payload());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Sec1Payload> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Sec1Reflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Sec1Payload() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Sec1Payload(Sec1Payload other) : this() {
    msg_ = other.msg_;
    switch (other.PayloadCase) {
      case PayloadOneofCase.Sc0:
        Sc0 = other.Sc0.Clone();
        break;
      case PayloadOneofCase.Sr0:
        Sr0 = other.Sr0.Clone();
        break;
      case PayloadOneofCase.Sc1:
        Sc1 = other.Sc1.Clone();
        break;
      case PayloadOneofCase.Sr1:
        Sr1 = other.Sr1.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Sec1Payload Clone() {
    return new Sec1Payload(this);
  }

  /// <summary>Field number for the "msg" field.</summary>
  public const int MsgFieldNumber = 1;
  private global::Sec1MsgType msg_ = global::Sec1MsgType.SessionCommand0;
  /// <summary>
  ///!&lt; Type of message 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Sec1MsgType Msg {
    get { return msg_; }
    set {
      msg_ = value;
    }
  }

  /// <summary>Field number for the "sc0" field.</summary>
  public const int Sc0FieldNumber = 20;
  /// <summary>
  ///!&lt; Payload data interpreted as Cmd0 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::SessionCmd0 Sc0 {
    get { return payloadCase_ == PayloadOneofCase.Sc0 ? (global::SessionCmd0) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Sc0;
    }
  }

  /// <summary>Field number for the "sr0" field.</summary>
  public const int Sr0FieldNumber = 21;
  /// <summary>
  ///!&lt; Payload data interpreted as Resp0 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::SessionResp0 Sr0 {
    get { return payloadCase_ == PayloadOneofCase.Sr0 ? (global::SessionResp0) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Sr0;
    }
  }

  /// <summary>Field number for the "sc1" field.</summary>
  public const int Sc1FieldNumber = 22;
  /// <summary>
  ///!&lt; Payload data interpreted as Cmd1 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::SessionCmd1 Sc1 {
    get { return payloadCase_ == PayloadOneofCase.Sc1 ? (global::SessionCmd1) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Sc1;
    }
  }

  /// <summary>Field number for the "sr1" field.</summary>
  public const int Sr1FieldNumber = 23;
  /// <summary>
  ///!&lt; Payload data interpreted as Resp1 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::SessionResp1 Sr1 {
    get { return payloadCase_ == PayloadOneofCase.Sr1 ? (global::SessionResp1) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Sr1;
    }
  }

  private object payload_;
  /// <summary>Enum of possible cases for the "payload" oneof.</summary>
  public enum PayloadOneofCase {
    None = 0,
    Sc0 = 20,
    Sr0 = 21,
    Sc1 = 22,
    Sr1 = 23,
  }
  private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PayloadOneofCase PayloadCase {
    get { return payloadCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPayload() {
    payloadCase_ = PayloadOneofCase.None;
    payload_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Sec1Payload);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Sec1Payload other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Msg != other.Msg) return false;
    if (!object.Equals(Sc0, other.Sc0)) return false;
    if (!object.Equals(Sr0, other.Sr0)) return false;
    if (!object.Equals(Sc1, other.Sc1)) return false;
    if (!object.Equals(Sr1, other.Sr1)) return false;
    if (PayloadCase != other.PayloadCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Msg != global::Sec1MsgType.SessionCommand0) hash ^= Msg.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Sc0) hash ^= Sc0.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Sr0) hash ^= Sr0.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Sc1) hash ^= Sc1.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Sr1) hash ^= Sr1.GetHashCode();
    hash ^= (int) payloadCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Msg != global::Sec1MsgType.SessionCommand0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Msg);
    }
    if (payloadCase_ == PayloadOneofCase.Sc0) {
      output.WriteRawTag(162, 1);
      output.WriteMessage(Sc0);
    }
    if (payloadCase_ == PayloadOneofCase.Sr0) {
      output.WriteRawTag(170, 1);
      output.WriteMessage(Sr0);
    }
    if (payloadCase_ == PayloadOneofCase.Sc1) {
      output.WriteRawTag(178, 1);
      output.WriteMessage(Sc1);
    }
    if (payloadCase_ == PayloadOneofCase.Sr1) {
      output.WriteRawTag(186, 1);
      output.WriteMessage(Sr1);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Msg != global::Sec1MsgType.SessionCommand0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Msg);
    }
    if (payloadCase_ == PayloadOneofCase.Sc0) {
      output.WriteRawTag(162, 1);
      output.WriteMessage(Sc0);
    }
    if (payloadCase_ == PayloadOneofCase.Sr0) {
      output.WriteRawTag(170, 1);
      output.WriteMessage(Sr0);
    }
    if (payloadCase_ == PayloadOneofCase.Sc1) {
      output.WriteRawTag(178, 1);
      output.WriteMessage(Sc1);
    }
    if (payloadCase_ == PayloadOneofCase.Sr1) {
      output.WriteRawTag(186, 1);
      output.WriteMessage(Sr1);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Msg != global::Sec1MsgType.SessionCommand0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Msg);
    }
    if (payloadCase_ == PayloadOneofCase.Sc0) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(Sc0);
    }
    if (payloadCase_ == PayloadOneofCase.Sr0) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(Sr0);
    }
    if (payloadCase_ == PayloadOneofCase.Sc1) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(Sc1);
    }
    if (payloadCase_ == PayloadOneofCase.Sr1) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(Sr1);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Sec1Payload other) {
    if (other == null) {
      return;
    }
    if (other.Msg != global::Sec1MsgType.SessionCommand0) {
      Msg = other.Msg;
    }
    switch (other.PayloadCase) {
      case PayloadOneofCase.Sc0:
        if (Sc0 == null) {
          Sc0 = new global::SessionCmd0();
        }
        Sc0.MergeFrom(other.Sc0);
        break;
      case PayloadOneofCase.Sr0:
        if (Sr0 == null) {
          Sr0 = new global::SessionResp0();
        }
        Sr0.MergeFrom(other.Sr0);
        break;
      case PayloadOneofCase.Sc1:
        if (Sc1 == null) {
          Sc1 = new global::SessionCmd1();
        }
        Sc1.MergeFrom(other.Sc1);
        break;
      case PayloadOneofCase.Sr1:
        if (Sr1 == null) {
          Sr1 = new global::SessionResp1();
        }
        Sr1.MergeFrom(other.Sr1);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Msg = (global::Sec1MsgType) input.ReadEnum();
          break;
        }
        case 162: {
          global::SessionCmd0 subBuilder = new global::SessionCmd0();
          if (payloadCase_ == PayloadOneofCase.Sc0) {
            subBuilder.MergeFrom(Sc0);
          }
          input.ReadMessage(subBuilder);
          Sc0 = subBuilder;
          break;
        }
        case 170: {
          global::SessionResp0 subBuilder = new global::SessionResp0();
          if (payloadCase_ == PayloadOneofCase.Sr0) {
            subBuilder.MergeFrom(Sr0);
          }
          input.ReadMessage(subBuilder);
          Sr0 = subBuilder;
          break;
        }
        case 178: {
          global::SessionCmd1 subBuilder = new global::SessionCmd1();
          if (payloadCase_ == PayloadOneofCase.Sc1) {
            subBuilder.MergeFrom(Sc1);
          }
          input.ReadMessage(subBuilder);
          Sc1 = subBuilder;
          break;
        }
        case 186: {
          global::SessionResp1 subBuilder = new global::SessionResp1();
          if (payloadCase_ == PayloadOneofCase.Sr1) {
            subBuilder.MergeFrom(Sr1);
          }
          input.ReadMessage(subBuilder);
          Sr1 = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Msg = (global::Sec1MsgType) input.ReadEnum();
          break;
        }
        case 162: {
          global::SessionCmd0 subBuilder = new global::SessionCmd0();
          if (payloadCase_ == PayloadOneofCase.Sc0) {
            subBuilder.MergeFrom(Sc0);
          }
          input.ReadMessage(subBuilder);
          Sc0 = subBuilder;
          break;
        }
        case 170: {
          global::SessionResp0 subBuilder = new global::SessionResp0();
          if (payloadCase_ == PayloadOneofCase.Sr0) {
            subBuilder.MergeFrom(Sr0);
          }
          input.ReadMessage(subBuilder);
          Sr0 = subBuilder;
          break;
        }
        case 178: {
          global::SessionCmd1 subBuilder = new global::SessionCmd1();
          if (payloadCase_ == PayloadOneofCase.Sc1) {
            subBuilder.MergeFrom(Sc1);
          }
          input.ReadMessage(subBuilder);
          Sc1 = subBuilder;
          break;
        }
        case 186: {
          global::SessionResp1 subBuilder = new global::SessionResp1();
          if (payloadCase_ == PayloadOneofCase.Sr1) {
            subBuilder.MergeFrom(Sr1);
          }
          input.ReadMessage(subBuilder);
          Sr1 = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
