// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sec2.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from sec2.proto</summary>
public static partial class Sec2Reflection {

  #region Descriptor
  /// <summary>File descriptor for sec2.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static Sec2Reflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpzZWMyLnByb3RvGg9jb25zdGFudHMucHJvdG8iPwoNUzJTZXNzaW9uQ21k",
          "MBIXCg9jbGllbnRfdXNlcm5hbWUYASABKAwSFQoNY2xpZW50X3B1YmtleRgC",
          "IAEoDCJVCg5TMlNlc3Npb25SZXNwMBIXCgZzdGF0dXMYASABKA4yBy5TdGF0",
          "dXMSFQoNZGV2aWNlX3B1YmtleRgCIAEoDBITCgtkZXZpY2Vfc2FsdBgDIAEo",
          "DCIlCg1TMlNlc3Npb25DbWQxEhQKDGNsaWVudF9wcm9vZhgBIAEoDCJVCg5T",
          "MlNlc3Npb25SZXNwMRIXCgZzdGF0dXMYASABKA4yBy5TdGF0dXMSFAoMZGV2",
          "aWNlX3Byb29mGAIgASgMEhQKDGRldmljZV9ub25jZRgDIAEoDCKxAQoLU2Vj",
          "MlBheWxvYWQSGQoDbXNnGAEgASgOMgwuU2VjMk1zZ1R5cGUSHQoDc2MwGBQg",
          "ASgLMg4uUzJTZXNzaW9uQ21kMEgAEh4KA3NyMBgVIAEoCzIPLlMyU2Vzc2lv",
          "blJlc3AwSAASHQoDc2MxGBYgASgLMg4uUzJTZXNzaW9uQ21kMUgAEh4KA3Ny",
          "MRgXIAEoCzIPLlMyU2Vzc2lvblJlc3AxSABCCQoHcGF5bG9hZCpvCgtTZWMy",
          "TXNnVHlwZRIWChJTMlNlc3Npb25fQ29tbWFuZDAQABIXChNTMlNlc3Npb25f",
          "UmVzcG9uc2UwEAESFgoSUzJTZXNzaW9uX0NvbW1hbmQxEAISFwoTUzJTZXNz",
          "aW9uX1Jlc3BvbnNlMRADYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ConstantsReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Sec2MsgType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::S2SessionCmd0), global::S2SessionCmd0.Parser, new[]{ "ClientUsername", "ClientPubkey" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::S2SessionResp0), global::S2SessionResp0.Parser, new[]{ "Status", "DevicePubkey", "DeviceSalt" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::S2SessionCmd1), global::S2SessionCmd1.Parser, new[]{ "ClientProof" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::S2SessionResp1), global::S2SessionResp1.Parser, new[]{ "Status", "DeviceProof", "DeviceNonce" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Sec2Payload), global::Sec2Payload.Parser, new[]{ "Msg", "Sc0", "Sr0", "Sc1", "Sr1" }, new[]{ "Payload" }, null, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
/// A message must be of type Cmd0 / Cmd1 / Resp0 / Resp1 
/// </summary>
public enum Sec2MsgType {
  [pbr::OriginalName("S2Session_Command0")] S2SessionCommand0 = 0,
  [pbr::OriginalName("S2Session_Response0")] S2SessionResponse0 = 1,
  [pbr::OriginalName("S2Session_Command1")] S2SessionCommand1 = 2,
  [pbr::OriginalName("S2Session_Response1")] S2SessionResponse1 = 3,
}

#endregion

#region Messages
/// <summary>
/// Data structure of Session command0 packet 
/// </summary>
public sealed partial class S2SessionCmd0 : pb::IMessage<S2SessionCmd0>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<S2SessionCmd0> _parser = new pb::MessageParser<S2SessionCmd0>(() => new S2SessionCmd0());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<S2SessionCmd0> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Sec2Reflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2SessionCmd0() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2SessionCmd0(S2SessionCmd0 other) : this() {
    clientUsername_ = other.clientUsername_;
    clientPubkey_ = other.clientPubkey_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2SessionCmd0 Clone() {
    return new S2SessionCmd0(this);
  }

  /// <summary>Field number for the "client_username" field.</summary>
  public const int ClientUsernameFieldNumber = 1;
  private pb::ByteString clientUsername_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString ClientUsername {
    get { return clientUsername_; }
    set {
      clientUsername_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "client_pubkey" field.</summary>
  public const int ClientPubkeyFieldNumber = 2;
  private pb::ByteString clientPubkey_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString ClientPubkey {
    get { return clientPubkey_; }
    set {
      clientPubkey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as S2SessionCmd0);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(S2SessionCmd0 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ClientUsername != other.ClientUsername) return false;
    if (ClientPubkey != other.ClientPubkey) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ClientUsername.Length != 0) hash ^= ClientUsername.GetHashCode();
    if (ClientPubkey.Length != 0) hash ^= ClientPubkey.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ClientUsername.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(ClientUsername);
    }
    if (ClientPubkey.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(ClientPubkey);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ClientUsername.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(ClientUsername);
    }
    if (ClientPubkey.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(ClientPubkey);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ClientUsername.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(ClientUsername);
    }
    if (ClientPubkey.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(ClientPubkey);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(S2SessionCmd0 other) {
    if (other == null) {
      return;
    }
    if (other.ClientUsername.Length != 0) {
      ClientUsername = other.ClientUsername;
    }
    if (other.ClientPubkey.Length != 0) {
      ClientPubkey = other.ClientPubkey;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          ClientUsername = input.ReadBytes();
          break;
        }
        case 18: {
          ClientPubkey = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          ClientUsername = input.ReadBytes();
          break;
        }
        case 18: {
          ClientPubkey = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Data structure of Session response0 packet 
/// </summary>
public sealed partial class S2SessionResp0 : pb::IMessage<S2SessionResp0>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<S2SessionResp0> _parser = new pb::MessageParser<S2SessionResp0>(() => new S2SessionResp0());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<S2SessionResp0> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Sec2Reflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2SessionResp0() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2SessionResp0(S2SessionResp0 other) : this() {
    status_ = other.status_;
    devicePubkey_ = other.devicePubkey_;
    deviceSalt_ = other.deviceSalt_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2SessionResp0 Clone() {
    return new S2SessionResp0(this);
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 1;
  private global::Status status_ = global::Status.Success;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Status Status {
    get { return status_; }
    set {
      status_ = value;
    }
  }

  /// <summary>Field number for the "device_pubkey" field.</summary>
  public const int DevicePubkeyFieldNumber = 2;
  private pb::ByteString devicePubkey_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString DevicePubkey {
    get { return devicePubkey_; }
    set {
      devicePubkey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "device_salt" field.</summary>
  public const int DeviceSaltFieldNumber = 3;
  private pb::ByteString deviceSalt_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString DeviceSalt {
    get { return deviceSalt_; }
    set {
      deviceSalt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as S2SessionResp0);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(S2SessionResp0 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Status != other.Status) return false;
    if (DevicePubkey != other.DevicePubkey) return false;
    if (DeviceSalt != other.DeviceSalt) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Status != global::Status.Success) hash ^= Status.GetHashCode();
    if (DevicePubkey.Length != 0) hash ^= DevicePubkey.GetHashCode();
    if (DeviceSalt.Length != 0) hash ^= DeviceSalt.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Status != global::Status.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Status);
    }
    if (DevicePubkey.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(DevicePubkey);
    }
    if (DeviceSalt.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(DeviceSalt);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Status != global::Status.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Status);
    }
    if (DevicePubkey.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(DevicePubkey);
    }
    if (DeviceSalt.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(DeviceSalt);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Status != global::Status.Success) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
    }
    if (DevicePubkey.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(DevicePubkey);
    }
    if (DeviceSalt.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(DeviceSalt);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(S2SessionResp0 other) {
    if (other == null) {
      return;
    }
    if (other.Status != global::Status.Success) {
      Status = other.Status;
    }
    if (other.DevicePubkey.Length != 0) {
      DevicePubkey = other.DevicePubkey;
    }
    if (other.DeviceSalt.Length != 0) {
      DeviceSalt = other.DeviceSalt;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Status = (global::Status) input.ReadEnum();
          break;
        }
        case 18: {
          DevicePubkey = input.ReadBytes();
          break;
        }
        case 26: {
          DeviceSalt = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Status = (global::Status) input.ReadEnum();
          break;
        }
        case 18: {
          DevicePubkey = input.ReadBytes();
          break;
        }
        case 26: {
          DeviceSalt = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Data structure of Session command1 packet 
/// </summary>
public sealed partial class S2SessionCmd1 : pb::IMessage<S2SessionCmd1>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<S2SessionCmd1> _parser = new pb::MessageParser<S2SessionCmd1>(() => new S2SessionCmd1());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<S2SessionCmd1> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Sec2Reflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2SessionCmd1() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2SessionCmd1(S2SessionCmd1 other) : this() {
    clientProof_ = other.clientProof_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2SessionCmd1 Clone() {
    return new S2SessionCmd1(this);
  }

  /// <summary>Field number for the "client_proof" field.</summary>
  public const int ClientProofFieldNumber = 1;
  private pb::ByteString clientProof_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString ClientProof {
    get { return clientProof_; }
    set {
      clientProof_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as S2SessionCmd1);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(S2SessionCmd1 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ClientProof != other.ClientProof) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ClientProof.Length != 0) hash ^= ClientProof.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ClientProof.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(ClientProof);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ClientProof.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(ClientProof);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ClientProof.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(ClientProof);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(S2SessionCmd1 other) {
    if (other == null) {
      return;
    }
    if (other.ClientProof.Length != 0) {
      ClientProof = other.ClientProof;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          ClientProof = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          ClientProof = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Data structure of Session response1 packet 
/// </summary>
public sealed partial class S2SessionResp1 : pb::IMessage<S2SessionResp1>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<S2SessionResp1> _parser = new pb::MessageParser<S2SessionResp1>(() => new S2SessionResp1());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<S2SessionResp1> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Sec2Reflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2SessionResp1() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2SessionResp1(S2SessionResp1 other) : this() {
    status_ = other.status_;
    deviceProof_ = other.deviceProof_;
    deviceNonce_ = other.deviceNonce_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2SessionResp1 Clone() {
    return new S2SessionResp1(this);
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 1;
  private global::Status status_ = global::Status.Success;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Status Status {
    get { return status_; }
    set {
      status_ = value;
    }
  }

  /// <summary>Field number for the "device_proof" field.</summary>
  public const int DeviceProofFieldNumber = 2;
  private pb::ByteString deviceProof_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString DeviceProof {
    get { return deviceProof_; }
    set {
      deviceProof_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "device_nonce" field.</summary>
  public const int DeviceNonceFieldNumber = 3;
  private pb::ByteString deviceNonce_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString DeviceNonce {
    get { return deviceNonce_; }
    set {
      deviceNonce_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as S2SessionResp1);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(S2SessionResp1 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Status != other.Status) return false;
    if (DeviceProof != other.DeviceProof) return false;
    if (DeviceNonce != other.DeviceNonce) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Status != global::Status.Success) hash ^= Status.GetHashCode();
    if (DeviceProof.Length != 0) hash ^= DeviceProof.GetHashCode();
    if (DeviceNonce.Length != 0) hash ^= DeviceNonce.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Status != global::Status.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Status);
    }
    if (DeviceProof.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(DeviceProof);
    }
    if (DeviceNonce.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(DeviceNonce);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Status != global::Status.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Status);
    }
    if (DeviceProof.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(DeviceProof);
    }
    if (DeviceNonce.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(DeviceNonce);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Status != global::Status.Success) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
    }
    if (DeviceProof.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(DeviceProof);
    }
    if (DeviceNonce.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(DeviceNonce);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(S2SessionResp1 other) {
    if (other == null) {
      return;
    }
    if (other.Status != global::Status.Success) {
      Status = other.Status;
    }
    if (other.DeviceProof.Length != 0) {
      DeviceProof = other.DeviceProof;
    }
    if (other.DeviceNonce.Length != 0) {
      DeviceNonce = other.DeviceNonce;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Status = (global::Status) input.ReadEnum();
          break;
        }
        case 18: {
          DeviceProof = input.ReadBytes();
          break;
        }
        case 26: {
          DeviceNonce = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Status = (global::Status) input.ReadEnum();
          break;
        }
        case 18: {
          DeviceProof = input.ReadBytes();
          break;
        }
        case 26: {
          DeviceNonce = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Payload structure of session data 
/// </summary>
public sealed partial class Sec2Payload : pb::IMessage<Sec2Payload>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Sec2Payload> _parser = new pb::MessageParser<Sec2Payload>(() => new Sec2Payload());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Sec2Payload> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Sec2Reflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Sec2Payload() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Sec2Payload(Sec2Payload other) : this() {
    msg_ = other.msg_;
    switch (other.PayloadCase) {
      case PayloadOneofCase.Sc0:
        Sc0 = other.Sc0.Clone();
        break;
      case PayloadOneofCase.Sr0:
        Sr0 = other.Sr0.Clone();
        break;
      case PayloadOneofCase.Sc1:
        Sc1 = other.Sc1.Clone();
        break;
      case PayloadOneofCase.Sr1:
        Sr1 = other.Sr1.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Sec2Payload Clone() {
    return new Sec2Payload(this);
  }

  /// <summary>Field number for the "msg" field.</summary>
  public const int MsgFieldNumber = 1;
  private global::Sec2MsgType msg_ = global::Sec2MsgType.S2SessionCommand0;
  /// <summary>
  ///!&lt; Type of message 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Sec2MsgType Msg {
    get { return msg_; }
    set {
      msg_ = value;
    }
  }

  /// <summary>Field number for the "sc0" field.</summary>
  public const int Sc0FieldNumber = 20;
  /// <summary>
  ///!&lt; Payload data interpreted as Cmd0 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::S2SessionCmd0 Sc0 {
    get { return payloadCase_ == PayloadOneofCase.Sc0 ? (global::S2SessionCmd0) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Sc0;
    }
  }

  /// <summary>Field number for the "sr0" field.</summary>
  public const int Sr0FieldNumber = 21;
  /// <summary>
  ///!&lt; Payload data interpreted as Resp0 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::S2SessionResp0 Sr0 {
    get { return payloadCase_ == PayloadOneofCase.Sr0 ? (global::S2SessionResp0) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Sr0;
    }
  }

  /// <summary>Field number for the "sc1" field.</summary>
  public const int Sc1FieldNumber = 22;
  /// <summary>
  ///!&lt; Payload data interpreted as Cmd1 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::S2SessionCmd1 Sc1 {
    get { return payloadCase_ == PayloadOneofCase.Sc1 ? (global::S2SessionCmd1) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Sc1;
    }
  }

  /// <summary>Field number for the "sr1" field.</summary>
  public const int Sr1FieldNumber = 23;
  /// <summary>
  ///!&lt; Payload data interpreted as Resp1 
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::S2SessionResp1 Sr1 {
    get { return payloadCase_ == PayloadOneofCase.Sr1 ? (global::S2SessionResp1) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Sr1;
    }
  }

  private object payload_;
  /// <summary>Enum of possible cases for the "payload" oneof.</summary>
  public enum PayloadOneofCase {
    None = 0,
    Sc0 = 20,
    Sr0 = 21,
    Sc1 = 22,
    Sr1 = 23,
  }
  private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PayloadOneofCase PayloadCase {
    get { return payloadCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPayload() {
    payloadCase_ = PayloadOneofCase.None;
    payload_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Sec2Payload);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Sec2Payload other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Msg != other.Msg) return false;
    if (!object.Equals(Sc0, other.Sc0)) return false;
    if (!object.Equals(Sr0, other.Sr0)) return false;
    if (!object.Equals(Sc1, other.Sc1)) return false;
    if (!object.Equals(Sr1, other.Sr1)) return false;
    if (PayloadCase != other.PayloadCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Msg != global::Sec2MsgType.S2SessionCommand0) hash ^= Msg.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Sc0) hash ^= Sc0.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Sr0) hash ^= Sr0.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Sc1) hash ^= Sc1.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Sr1) hash ^= Sr1.GetHashCode();
    hash ^= (int) payloadCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Msg != global::Sec2MsgType.S2SessionCommand0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Msg);
    }
    if (payloadCase_ == PayloadOneofCase.Sc0) {
      output.WriteRawTag(162, 1);
      output.WriteMessage(Sc0);
    }
    if (payloadCase_ == PayloadOneofCase.Sr0) {
      output.WriteRawTag(170, 1);
      output.WriteMessage(Sr0);
    }
    if (payloadCase_ == PayloadOneofCase.Sc1) {
      output.WriteRawTag(178, 1);
      output.WriteMessage(Sc1);
    }
    if (payloadCase_ == PayloadOneofCase.Sr1) {
      output.WriteRawTag(186, 1);
      output.WriteMessage(Sr1);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Msg != global::Sec2MsgType.S2SessionCommand0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Msg);
    }
    if (payloadCase_ == PayloadOneofCase.Sc0) {
      output.WriteRawTag(162, 1);
      output.WriteMessage(Sc0);
    }
    if (payloadCase_ == PayloadOneofCase.Sr0) {
      output.WriteRawTag(170, 1);
      output.WriteMessage(Sr0);
    }
    if (payloadCase_ == PayloadOneofCase.Sc1) {
      output.WriteRawTag(178, 1);
      output.WriteMessage(Sc1);
    }
    if (payloadCase_ == PayloadOneofCase.Sr1) {
      output.WriteRawTag(186, 1);
      output.WriteMessage(Sr1);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Msg != global::Sec2MsgType.S2SessionCommand0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Msg);
    }
    if (payloadCase_ == PayloadOneofCase.Sc0) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(Sc0);
    }
    if (payloadCase_ == PayloadOneofCase.Sr0) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(Sr0);
    }
    if (payloadCase_ == PayloadOneofCase.Sc1) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(Sc1);
    }
    if (payloadCase_ == PayloadOneofCase.Sr1) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(Sr1);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Sec2Payload other) {
    if (other == null) {
      return;
    }
    if (other.Msg != global::Sec2MsgType.S2SessionCommand0) {
      Msg = other.Msg;
    }
    switch (other.PayloadCase) {
      case PayloadOneofCase.Sc0:
        if (Sc0 == null) {
          Sc0 = new global::S2SessionCmd0();
        }
        Sc0.MergeFrom(other.Sc0);
        break;
      case PayloadOneofCase.Sr0:
        if (Sr0 == null) {
          Sr0 = new global::S2SessionResp0();
        }
        Sr0.MergeFrom(other.Sr0);
        break;
      case PayloadOneofCase.Sc1:
        if (Sc1 == null) {
          Sc1 = new global::S2SessionCmd1();
        }
        Sc1.MergeFrom(other.Sc1);
        break;
      case PayloadOneofCase.Sr1:
        if (Sr1 == null) {
          Sr1 = new global::S2SessionResp1();
        }
        Sr1.MergeFrom(other.Sr1);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Msg = (global::Sec2MsgType) input.ReadEnum();
          break;
        }
        case 162: {
          global::S2SessionCmd0 subBuilder = new global::S2SessionCmd0();
          if (payloadCase_ == PayloadOneofCase.Sc0) {
            subBuilder.MergeFrom(Sc0);
          }
          input.ReadMessage(subBuilder);
          Sc0 = subBuilder;
          break;
        }
        case 170: {
          global::S2SessionResp0 subBuilder = new global::S2SessionResp0();
          if (payloadCase_ == PayloadOneofCase.Sr0) {
            subBuilder.MergeFrom(Sr0);
          }
          input.ReadMessage(subBuilder);
          Sr0 = subBuilder;
          break;
        }
        case 178: {
          global::S2SessionCmd1 subBuilder = new global::S2SessionCmd1();
          if (payloadCase_ == PayloadOneofCase.Sc1) {
            subBuilder.MergeFrom(Sc1);
          }
          input.ReadMessage(subBuilder);
          Sc1 = subBuilder;
          break;
        }
        case 186: {
          global::S2SessionResp1 subBuilder = new global::S2SessionResp1();
          if (payloadCase_ == PayloadOneofCase.Sr1) {
            subBuilder.MergeFrom(Sr1);
          }
          input.ReadMessage(subBuilder);
          Sr1 = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Msg = (global::Sec2MsgType) input.ReadEnum();
          break;
        }
        case 162: {
          global::S2SessionCmd0 subBuilder = new global::S2SessionCmd0();
          if (payloadCase_ == PayloadOneofCase.Sc0) {
            subBuilder.MergeFrom(Sc0);
          }
          input.ReadMessage(subBuilder);
          Sc0 = subBuilder;
          break;
        }
        case 170: {
          global::S2SessionResp0 subBuilder = new global::S2SessionResp0();
          if (payloadCase_ == PayloadOneofCase.Sr0) {
            subBuilder.MergeFrom(Sr0);
          }
          input.ReadMessage(subBuilder);
          Sr0 = subBuilder;
          break;
        }
        case 178: {
          global::S2SessionCmd1 subBuilder = new global::S2SessionCmd1();
          if (payloadCase_ == PayloadOneofCase.Sc1) {
            subBuilder.MergeFrom(Sc1);
          }
          input.ReadMessage(subBuilder);
          Sc1 = subBuilder;
          break;
        }
        case 186: {
          global::S2SessionResp1 subBuilder = new global::S2SessionResp1();
          if (payloadCase_ == PayloadOneofCase.Sr1) {
            subBuilder.MergeFrom(Sr1);
          }
          input.ReadMessage(subBuilder);
          Sr1 = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
