// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: constants.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from constants.proto</summary>
public static partial class ConstantsReflection {

  #region Descriptor
  /// <summary>File descriptor for constants.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ConstantsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9jb25zdGFudHMucHJvdG8qnwEKBlN0YXR1cxILCgdTdWNjZXNzEAASFAoQ",
          "SW52YWxpZFNlY1NjaGVtZRABEhAKDEludmFsaWRQcm90bxACEhMKD1Rvb01h",
          "bnlTZXNzaW9ucxADEhMKD0ludmFsaWRBcmd1bWVudBAEEhEKDUludGVybmFs",
          "RXJyb3IQBRIPCgtDcnlwdG9FcnJvchAGEhIKDkludmFsaWRTZXNzaW9uEAdi",
          "BnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Status), }, null, null));
  }
  #endregion

}
#region Enums
/// <summary>
/// Allowed values for the status
/// of a protocomm instance 
/// </summary>
public enum Status {
  [pbr::OriginalName("Success")] Success = 0,
  [pbr::OriginalName("InvalidSecScheme")] InvalidSecScheme = 1,
  [pbr::OriginalName("InvalidProto")] InvalidProto = 2,
  [pbr::OriginalName("TooManySessions")] TooManySessions = 3,
  [pbr::OriginalName("InvalidArgument")] InvalidArgument = 4,
  [pbr::OriginalName("InternalError")] InternalError = 5,
  [pbr::OriginalName("CryptoError")] CryptoError = 6,
  [pbr::OriginalName("InvalidSession")] InvalidSession = 7,
}

#endregion


#endregion Designer generated code
